
services:
  doca-hq:
    build: .
    container_name: doca-hq
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doca-hq.rule=Host(`hq.docaperformance.com.br`)"
      - "traefik.http.routers.doca-hq.entrypoints=websecure"
      - "traefik.http.routers.doca-hq.tls.certresolver=mytlschallenge"
      - "traefik.http.services.doca-hq.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true